### ISSUE TITLE
New upstream for Arc theme

### ISSUE THREAD

**Issue by mati865** [snapcrafters/gtk-common-themes#1]
Hello,
@horst3180 (creator of Arc theme) has beed missing for a long time.
There is new community driven fork: https://github.com/NicoHood/arc-theme

**Comment by jhenstridge** [comment]
This has been done here:

https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/commit/8c80f385d6280a1a4018a52fb3afaeeca95d32e6
