### ISSUE TITLE
Suru icon theme symlink doesn't work

### ISSUE THREAD

**Issue by jhenstridge** [snapcrafters/gtk-common-themes#13]
Currently gtk-common-themes includes the following symlink:

    $ ls -l /snap/gtk-common-themes/current/share/icons/
    ...
    lrwxrwxrwx  1 root root  12 Sep 11 23:56 Suru -> communitheme

This is then referenced as a source directory for the icon-themes content slot, which then fails to mount in applications that plug the interface:

    $ sudo /usr/lib/snapd/snap-discard-ns gnome-calculator
    $ gnome-calculator 
    main.go:192: cannot change mount namespace of snap "gnome-calculator" according to change mount (/snap/gtk-common-themes/701/share/icons/Suru /snap/gnome-calculator/222/data-dir/icons/Suru none bind,ro 0 0): cannot use "/snap/gtk-common-themes/701/share/icons/Suru" as bind-mount source: not a directory

If we're going to provide the Suru icon theme, then it needs to be a real directory rather than a symlink.  If we want to have it use icons from communitheme (not Yaru??), then that should be done through icon theme inheritance.

**Comment by kenvandine** [comment]
Migrated issue to https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/1
