### ISSUE TITLE
Themes might not be properly mounted when they contain a symlink

### ISSUE THREAD

**Issue by 3v1n0** [snapcrafters/gtk-common-themes#16]
More details at https://bugs.launchpad.net/snappy/+bug/1781906

`ŧelegram-desktop` fails when refreshing, but I guess others might too.

**Comment by stolowski** [comment]
It also results in a series of errors on snap run --shell (with a gnome-calculator snap for example): https://bugs.launchpad.net/snapd/+bug/1780459

**Comment by jhenstridge** [comment]
This should be addressed by https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/merge_requests/8

The only concern now is whether to leave what I've added to the snapcraft.yaml there, or have it as a build option for Yaru itself (I'm leaning towards adding it to Yaru so as not to split the build info).
